import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        serif: ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      colors: {
        'kern-bg': 'var(--kern-bg)',
        'kern-surface': 'var(--kern-surface)',
        'kern-surface-2': 'var(--kern-surface-2)',
        'kern-border': 'var(--kern-border)',
        'kern-border-2': 'var(--kern-border-2)',
        'kern-text': 'var(--kern-text)',
        'kern-text-2': 'var(--kern-text-2)',
        'kern-text-3': 'var(--kern-text-3)',
        'kern-accent': 'var(--kern-accent)',
        'kern-accent-2': 'var(--kern-accent-2)',
        'kern-accent-hover': 'var(--kern-accent-hover)',
        'kern-on-accent': 'var(--kern-on-accent)',
        'kern-danger': 'var(--kern-danger)',
        'kern-success': 'var(--kern-success)',
        'kern-warning': 'var(--kern-warning)',
        'kern-accent-tint': 'var(--accent-tint)',
        'kern-accent-light': 'var(--accent-light)',
        'kern-accent-deep': 'var(--accent-deep)',
        'ds-bg-0': 'var(--bg-0)',
        'ds-bg-1': 'var(--bg-1)',
        'ds-bg-2': 'var(--bg-2)',
        'ds-bg-3': 'var(--bg-3)',
        'ds-bg-4': 'var(--bg-4)',
        'ds-border-subtle': 'var(--border-subtle)',
        'ds-border-default': 'var(--border-default)',
        'ds-border-strong': 'var(--border-strong)',
        'ds-text-primary': 'var(--text-primary)',
        'ds-text-secondary': 'var(--text-secondary)',
        'ds-text-tertiary': 'var(--text-tertiary)',
        'ds-accent': 'var(--accent)',
        'ds-red': 'var(--color-red)',
        'ds-orange': 'var(--color-orange)',
        'ds-yellow': 'var(--color-yellow)',
        'ds-green': 'var(--color-green)',
        'ds-teal': 'var(--color-teal)',
        'ds-blue': 'var(--color-blue)',
        'ds-purple': 'var(--color-purple)',
        'ds-pink': 'var(--color-pink)',
        'ds-gray': 'var(--color-gray)',
      },
      borderRadius: {
        DEFAULT: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
        'kern-sm': 'var(--radius-sm)',
        'kern-md': 'var(--radius-md)',
        'kern-lg': 'var(--radius-lg)',
        'kern-xl': 'var(--radius-xl)',
        'ds-sm': 'var(--radius-sm)',
        'ds-md': 'var(--radius-md)',
        'ds-lg': 'var(--radius-lg)',
      },
      boxShadow: {
        'ds-sm': 'var(--shadow-sm)',
        'ds-md': 'var(--shadow-md)',
        'ds-lg': 'var(--shadow-lg)',
      },
      transitionDuration: {
        'ds-fast': '80ms',
        'ds-default': '150ms',
      },
      minHeight: {
        /** Fills viewport below fixed topbar; keep in sync with --layout-topbar-h in index.css */
        'shell-main': 'calc(100vh - var(--layout-topbar-h))',
      },
      keyframes: {
        'kern-upload-bar': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(350%)' },
        },
      },
      animation: {
        'kern-upload-bar': 'kern-upload-bar 1.1s ease-in-out infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
