import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AirVent,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  Album,
  AlignCenter,
  AlignJustify,
  Anchor,
  Apple,
  Archive,
  ArchiveRestore,
  Armchair,
  AtSign,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCent,
  BadgeDollarSign,
  BadgeEuro,
  BadgeInfo,
  BadgePercent,
  BadgeRussianRuble,
  Balloon,
  Banana,
  Banknote,
  BarChart2,
  BarChart3,
  BarChart4,
  BarChartHorizontalBig,
  Bath,
  BatteryFull,
  BatteryLow,
  Beaker,
  BedDouble,
  Beef,
  Beer,
  Bell,
  BellDot,
  BellOff,
  BellRing,
  Bike,
  Binary,
  Bird,
  Bitcoin,
  Blend,
  Bluetooth,
  Book,
  BookCopy,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  BrickWall,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseConveyorBelt,
  BriefcaseMedical,
  Brush,
  Bug,
  Building2,
  Bus,
  BusFront,
  Cable,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Camera,
  CameraOff,
  Candy,
  Car,
  CarFront,
  Carrot,
  Cat,
  Church,
  CircleDollarSign,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPaste,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudRain,
  CloudSnow,
  Club,
  Code,
  Code2,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  Cuboid,
  Database,
  DatabaseBackup,
  Dessert,
  Dices,
  Disc3,
  DiscAlbum,
  Dog,
  DollarSign,
  Donut,
  DoorOpen,
  Download,
  Drama,
  Drill,
  Droplet,
  Drum,
  Dumbbell,
  Ear,
  Egg,
  EggFried,
  EthernetPort,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  Fan,
  Feather,
  File,
  FileArchive,
  FileAudio,
  FileCode2,
  FileJson,
  FileSpreadsheet,
  FileText,
  FileVideo,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Focus,
  Folder,
  FolderKanban,
  FolderOpen,
  Footprints,
  Frame,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  HandCoins,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Highlighter,
  History,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  House,
  IceCream,
  IceCreamCone,
  IdCard,
  Image,
  ImageOff,
  ImagePlus,
  Inbox,
  Infinity,
  Instagram,
  Joystick,
  Kanban,
  KanbanSquare,
  Key,
  KeyRound,
  Keyboard,
  LampDesk,
  Landmark,
  Laptop,
  Layers,
  Layers2,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  LeafyGreen,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  Linkedin,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  ListTree,
  Lock,
  LockOpen,
  Lollipop,
  Magnet,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Martini,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  MicOff,
  Microscope,
  Milestone,
  Milk,
  Monitor,
  MonitorDot,
  MonitorPlay,
  Moon,
  MountainSnow,
  Mouse,
  Music,
  Music2,
  Music3,
  Network,
  Newspaper,
  Notebook,
  NotepadText,
  Nut,
  OctagonAlert,
  Package2,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  PcCase,
  PenLine,
  PencilLine,
  Percent,
  Phone,
  PhoneCall,
  Piano,
  Pickaxe,
  PictureInPicture2,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug2,
  Podcast,
  Power,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radio,
  Receipt,
  Recycle,
  Refrigerator,
  Regex,
  Rocket,
  Router,
  Rss,
  Ruler,
  Sailboat,
  Sandwich,
  Satellite,
  SatelliteDish,
  SaveAll,
  Scale3d,
  School,
  Scissors,
  ScrollText,
  Search,
  SearchX,
  Send,
  Server,
  ServerCog,
  ServerCrash,
  Settings,
  Shapes,
  Share2,
  Sheet,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  Smartphone,
  SmartphoneCharging,
  SmilePlus,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Spline,
  Sprout,
  SquarePen,
  SquareStack,
  Stamp,
  Star,
  StarHalf,
  Stethoscope,
  StickyNote,
  Store,
  SunMedium,
  SunSnow,
  Swords,
  Syringe,
  Table2,
  Tablet,
  TabletSmartphone,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  Terminal,
  ThermometerSun,
  Ticket,
  Timer,
  TrainFront,
  Trash,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  TvMinimal,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  Usb,
  User,
  UserPlus,
  UserRound,
  UserRoundCheck,
  Users,
  UsersRound,
  Utensils,
  Video,
  VideoOff,
  Voicemail,
  Volume2,
  Wallet,
  Wand2,
  Warehouse,
  Watch,
  Waves,
  Webcam,
  Wheat,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

export type CollectionLucideOption = { name: string; label: string; Icon: LucideIcon };

/** Curated Lucide icons for collections (name = lucide-react export). */
export const COLLECTION_LUCIDE_OPTIONS: readonly CollectionLucideOption[] = [
  { name: 'Activity', label: 'Activity', Icon: Activity },
  { name: 'AirVent', label: 'Air Vent', Icon: AirVent },
  { name: 'Airplay', label: 'Airplay', Icon: Airplay },
  { name: 'AlarmClock', label: 'Alarm Clock', Icon: AlarmClock },
  { name: 'AlarmClockCheck', label: 'Alarm Clock Check', Icon: AlarmClockCheck },
  { name: 'Album', label: 'Album', Icon: Album },
  { name: 'AlignCenter', label: 'Align Center', Icon: AlignCenter },
  { name: 'AlignJustify', label: 'Align Justify', Icon: AlignJustify },
  { name: 'Anchor', label: 'Anchor', Icon: Anchor },
  { name: 'Apple', label: 'Apple', Icon: Apple },
  { name: 'Archive', label: 'Archive', Icon: Archive },
  { name: 'ArchiveRestore', label: 'Archive Restore', Icon: ArchiveRestore },
  { name: 'Armchair', label: 'Armchair', Icon: Armchair },
  { name: 'AtSign', label: 'At Sign', Icon: AtSign },
  { name: 'Award', label: 'Award', Icon: Award },
  { name: 'Axe', label: 'Axe', Icon: Axe },
  { name: 'Baby', label: 'Baby', Icon: Baby },
  { name: 'Backpack', label: 'Backpack', Icon: Backpack },
  { name: 'BadgeCent', label: 'Badge Cent', Icon: BadgeCent },
  { name: 'BadgeDollarSign', label: 'Badge Dollar Sign', Icon: BadgeDollarSign },
  { name: 'BadgeEuro', label: 'Badge Euro', Icon: BadgeEuro },
  { name: 'BadgeInfo', label: 'Badge Info', Icon: BadgeInfo },
  { name: 'BadgePercent', label: 'Badge Percent', Icon: BadgePercent },
  { name: 'BadgeRussianRuble', label: 'Badge Russian Ruble', Icon: BadgeRussianRuble },
  { name: 'Balloon', label: 'Balloon', Icon: Balloon },
  { name: 'Banana', label: 'Banana', Icon: Banana },
  { name: 'Banknote', label: 'Banknote', Icon: Banknote },
  { name: 'BarChart2', label: 'Bar Chart 2', Icon: BarChart2 },
  { name: 'BarChart3', label: 'Bar Chart 3', Icon: BarChart3 },
  { name: 'BarChart4', label: 'Bar Chart 4', Icon: BarChart4 },
  { name: 'BarChartHorizontalBig', label: 'Bar Chart Horizontal Big', Icon: BarChartHorizontalBig },
  { name: 'Bath', label: 'Bath', Icon: Bath },
  { name: 'BatteryFull', label: 'Battery Full', Icon: BatteryFull },
  { name: 'BatteryLow', label: 'Battery Low', Icon: BatteryLow },
  { name: 'Beaker', label: 'Beaker', Icon: Beaker },
  { name: 'BedDouble', label: 'Bed Double', Icon: BedDouble },
  { name: 'Beef', label: 'Beef', Icon: Beef },
  { name: 'Beer', label: 'Beer', Icon: Beer },
  { name: 'Bell', label: 'Bell', Icon: Bell },
  { name: 'BellDot', label: 'Bell Dot', Icon: BellDot },
  { name: 'BellOff', label: 'Bell Off', Icon: BellOff },
  { name: 'BellRing', label: 'Bell Ring', Icon: BellRing },
  { name: 'Bike', label: 'Bike', Icon: Bike },
  { name: 'Binary', label: 'Binary', Icon: Binary },
  { name: 'Bird', label: 'Bird', Icon: Bird },
  { name: 'Bitcoin', label: 'Bitcoin', Icon: Bitcoin },
  { name: 'Blend', label: 'Blend', Icon: Blend },
  { name: 'Bluetooth', label: 'Bluetooth', Icon: Bluetooth },
  { name: 'Book', label: 'Book', Icon: Book },
  { name: 'BookCopy', label: 'Book Copy', Icon: BookCopy },
  { name: 'BookMarked', label: 'Book Marked', Icon: BookMarked },
  { name: 'BookOpen', label: 'Book Open', Icon: BookOpen },
  { name: 'Bookmark', label: 'Bookmark', Icon: Bookmark },
  { name: 'Bot', label: 'Bot', Icon: Bot },
  { name: 'Box', label: 'Box', Icon: Box },
  { name: 'Brain', label: 'Brain', Icon: Brain },
  { name: 'BrickWall', label: 'Brick Wall', Icon: BrickWall },
  { name: 'Briefcase', label: 'Briefcase', Icon: Briefcase },
  { name: 'BriefcaseBusiness', label: 'Briefcase Business', Icon: BriefcaseBusiness },
  { name: 'BriefcaseConveyorBelt', label: 'Briefcase Conveyor Belt', Icon: BriefcaseConveyorBelt },
  { name: 'BriefcaseMedical', label: 'Briefcase Medical', Icon: BriefcaseMedical },
  { name: 'Brush', label: 'Brush', Icon: Brush },
  { name: 'Bug', label: 'Bug', Icon: Bug },
  { name: 'Building2', label: 'Building 2', Icon: Building2 },
  { name: 'Bus', label: 'Bus', Icon: Bus },
  { name: 'BusFront', label: 'Bus Front', Icon: BusFront },
  { name: 'Cable', label: 'Cable', Icon: Cable },
  { name: 'Cake', label: 'Cake', Icon: Cake },
  { name: 'CakeSlice', label: 'Cake Slice', Icon: CakeSlice },
  { name: 'Calculator', label: 'Calculator', Icon: Calculator },
  { name: 'Calendar', label: 'Calendar', Icon: Calendar },
  { name: 'CalendarCheck2', label: 'Calendar Check 2', Icon: CalendarCheck2 },
  { name: 'CalendarClock', label: 'Calendar Clock', Icon: CalendarClock },
  { name: 'CalendarDays', label: 'Calendar Days', Icon: CalendarDays },
  { name: 'CalendarRange', label: 'Calendar Range', Icon: CalendarRange },
  { name: 'Camera', label: 'Camera', Icon: Camera },
  { name: 'CameraOff', label: 'Camera Off', Icon: CameraOff },
  { name: 'Candy', label: 'Candy', Icon: Candy },
  { name: 'Car', label: 'Car', Icon: Car },
  { name: 'CarFront', label: 'Car Front', Icon: CarFront },
  { name: 'Carrot', label: 'Carrot', Icon: Carrot },
  { name: 'Cat', label: 'Cat', Icon: Cat },
  { name: 'Church', label: 'Church', Icon: Church },
  { name: 'CircleDollarSign', label: 'Circle Dollar Sign', Icon: CircleDollarSign },
  { name: 'Clapperboard', label: 'Clapperboard', Icon: Clapperboard },
  { name: 'Clipboard', label: 'Clipboard', Icon: Clipboard },
  { name: 'ClipboardCheck', label: 'Clipboard Check', Icon: ClipboardCheck },
  { name: 'ClipboardCopy', label: 'Clipboard Copy', Icon: ClipboardCopy },
  { name: 'ClipboardList', label: 'Clipboard List', Icon: ClipboardList },
  { name: 'ClipboardPaste', label: 'Clipboard Paste', Icon: ClipboardPaste },
  { name: 'Clock', label: 'Clock', Icon: Clock },
  { name: 'Cloud', label: 'Cloud', Icon: Cloud },
  { name: 'CloudDrizzle', label: 'Cloud Drizzle', Icon: CloudDrizzle },
  { name: 'CloudRain', label: 'Cloud Rain', Icon: CloudRain },
  { name: 'CloudSnow', label: 'Cloud Snow', Icon: CloudSnow },
  { name: 'Club', label: 'Club', Icon: Club },
  { name: 'Code', label: 'Code', Icon: Code },
  { name: 'Code2', label: 'Code 2', Icon: Code2 },
  { name: 'Coffee', label: 'Coffee', Icon: Coffee },
  { name: 'Cog', label: 'Cog', Icon: Cog },
  { name: 'Coins', label: 'Coins', Icon: Coins },
  { name: 'Compass', label: 'Compass', Icon: Compass },
  { name: 'Construction', label: 'Construction', Icon: Construction },
  { name: 'Cookie', label: 'Cookie', Icon: Cookie },
  { name: 'CookingPot', label: 'Cooking Pot', Icon: CookingPot },
  { name: 'Cpu', label: 'Cpu', Icon: Cpu },
  { name: 'CreditCard', label: 'Credit Card', Icon: CreditCard },
  { name: 'Croissant', label: 'Croissant', Icon: Croissant },
  { name: 'Crown', label: 'Crown', Icon: Crown },
  { name: 'Cuboid', label: 'Cuboid', Icon: Cuboid },
  { name: 'Database', label: 'Database', Icon: Database },
  { name: 'DatabaseBackup', label: 'Database Backup', Icon: DatabaseBackup },
  { name: 'Dessert', label: 'Dessert', Icon: Dessert },
  { name: 'Dices', label: 'Dices', Icon: Dices },
  { name: 'Disc3', label: 'Disc 3', Icon: Disc3 },
  { name: 'DiscAlbum', label: 'Disc Album', Icon: DiscAlbum },
  { name: 'Dog', label: 'Dog', Icon: Dog },
  { name: 'DollarSign', label: 'Dollar Sign', Icon: DollarSign },
  { name: 'Donut', label: 'Donut', Icon: Donut },
  { name: 'DoorOpen', label: 'Door Open', Icon: DoorOpen },
  { name: 'Download', label: 'Download', Icon: Download },
  { name: 'Drama', label: 'Drama', Icon: Drama },
  { name: 'Drill', label: 'Drill', Icon: Drill },
  { name: 'Droplet', label: 'Droplet', Icon: Droplet },
  { name: 'Drum', label: 'Drum', Icon: Drum },
  { name: 'Dumbbell', label: 'Dumbbell', Icon: Dumbbell },
  { name: 'Ear', label: 'Ear', Icon: Ear },
  { name: 'Egg', label: 'Egg', Icon: Egg },
  { name: 'EggFried', label: 'Egg Fried', Icon: EggFried },
  { name: 'EthernetPort', label: 'Ethernet Port', Icon: EthernetPort },
  { name: 'Expand', label: 'Expand', Icon: Expand },
  { name: 'ExternalLink', label: 'External Link', Icon: ExternalLink },
  { name: 'Eye', label: 'Eye', Icon: Eye },
  { name: 'EyeOff', label: 'Eye Off', Icon: EyeOff },
  { name: 'Facebook', label: 'Facebook', Icon: Facebook },
  { name: 'Factory', label: 'Factory', Icon: Factory },
  { name: 'Fan', label: 'Fan', Icon: Fan },
  { name: 'Feather', label: 'Feather', Icon: Feather },
  { name: 'File', label: 'File', Icon: File },
  { name: 'FileArchive', label: 'File Archive', Icon: FileArchive },
  { name: 'FileAudio', label: 'File Audio', Icon: FileAudio },
  { name: 'FileCode2', label: 'File Code 2', Icon: FileCode2 },
  { name: 'FileJson', label: 'File Json', Icon: FileJson },
  { name: 'FileSpreadsheet', label: 'File Spreadsheet', Icon: FileSpreadsheet },
  { name: 'FileText', label: 'File Text', Icon: FileText },
  { name: 'FileVideo', label: 'File Video', Icon: FileVideo },
  { name: 'Film', label: 'Film', Icon: Film },
  { name: 'Filter', label: 'Filter', Icon: Filter },
  { name: 'Fish', label: 'Fish', Icon: Fish },
  { name: 'Flag', label: 'Flag', Icon: Flag },
  { name: 'Flame', label: 'Flame', Icon: Flame },
  { name: 'FlaskConical', label: 'Flask Conical', Icon: FlaskConical },
  { name: 'Flower2', label: 'Flower 2', Icon: Flower2 },
  { name: 'Focus', label: 'Focus', Icon: Focus },
  { name: 'Folder', label: 'Folder', Icon: Folder },
  { name: 'FolderKanban', label: 'Folder Kanban', Icon: FolderKanban },
  { name: 'FolderOpen', label: 'Folder Open', Icon: FolderOpen },
  { name: 'Footprints', label: 'Footprints', Icon: Footprints },
  { name: 'Frame', label: 'Frame', Icon: Frame },
  { name: 'Fuel', label: 'Fuel', Icon: Fuel },
  { name: 'Gamepad2', label: 'Gamepad 2', Icon: Gamepad2 },
  { name: 'Gauge', label: 'Gauge', Icon: Gauge },
  { name: 'Gem', label: 'Gem', Icon: Gem },
  { name: 'Ghost', label: 'Ghost', Icon: Ghost },
  { name: 'Gift', label: 'Gift', Icon: Gift },
  { name: 'GlassWater', label: 'Glass Water', Icon: GlassWater },
  { name: 'Globe', label: 'Globe', Icon: Globe },
  { name: 'GraduationCap', label: 'Graduation Cap', Icon: GraduationCap },
  { name: 'Grape', label: 'Grape', Icon: Grape },
  { name: 'Guitar', label: 'Guitar', Icon: Guitar },
  { name: 'Hammer', label: 'Hammer', Icon: Hammer },
  { name: 'HandCoins', label: 'Hand Coins', Icon: HandCoins },
  { name: 'HardDrive', label: 'Hard Drive', Icon: HardDrive },
  { name: 'HardHat', label: 'Hard Hat', Icon: HardHat },
  { name: 'Hash', label: 'Hash', Icon: Hash },
  { name: 'Headphones', label: 'Headphones', Icon: Headphones },
  { name: 'Heart', label: 'Heart', Icon: Heart },
  { name: 'HeartPulse', label: 'Heart Pulse', Icon: HeartPulse },
  { name: 'Hexagon', label: 'Hexagon', Icon: Hexagon },
  { name: 'Highlighter', label: 'Highlighter', Icon: Highlighter },
  { name: 'History', label: 'History', Icon: History },
  { name: 'Home', label: 'Home', Icon: Home },
  { name: 'Hospital', label: 'Hospital', Icon: Hospital },
  { name: 'Hotel', label: 'Hotel', Icon: Hotel },
  { name: 'Hourglass', label: 'Hourglass', Icon: Hourglass },
  { name: 'House', label: 'House', Icon: House },
  { name: 'IceCream', label: 'Ice Cream', Icon: IceCream },
  { name: 'IceCreamCone', label: 'Ice Cream Cone', Icon: IceCreamCone },
  { name: 'IdCard', label: 'Id Card', Icon: IdCard },
  { name: 'Image', label: 'Image', Icon: Image },
  { name: 'ImageOff', label: 'Image Off', Icon: ImageOff },
  { name: 'ImagePlus', label: 'Image Plus', Icon: ImagePlus },
  { name: 'Inbox', label: 'Inbox', Icon: Inbox },
  { name: 'Infinity', label: 'Infinity', Icon: Infinity },
  { name: 'Instagram', label: 'Instagram', Icon: Instagram },
  { name: 'Joystick', label: 'Joystick', Icon: Joystick },
  { name: 'Kanban', label: 'Kanban', Icon: Kanban },
  { name: 'KanbanSquare', label: 'Kanban Square', Icon: KanbanSquare },
  { name: 'Key', label: 'Key', Icon: Key },
  { name: 'KeyRound', label: 'Key Round', Icon: KeyRound },
  { name: 'Keyboard', label: 'Keyboard', Icon: Keyboard },
  { name: 'LampDesk', label: 'Lamp Desk', Icon: LampDesk },
  { name: 'Landmark', label: 'Landmark', Icon: Landmark },
  { name: 'Laptop', label: 'Laptop', Icon: Laptop },
  { name: 'Layers', label: 'Layers', Icon: Layers },
  { name: 'Layers2', label: 'Layers 2', Icon: Layers2 },
  { name: 'Layers3', label: 'Layers 3', Icon: Layers3 },
  { name: 'LayoutDashboard', label: 'Layout Dashboard', Icon: LayoutDashboard },
  { name: 'LayoutGrid', label: 'Layout Grid', Icon: LayoutGrid },
  { name: 'Leaf', label: 'Leaf', Icon: Leaf },
  { name: 'LeafyGreen', label: 'Leafy Green', Icon: LeafyGreen },
  { name: 'Library', label: 'Library', Icon: Library },
  { name: 'LibraryBig', label: 'Library Big', Icon: LibraryBig },
  { name: 'LifeBuoy', label: 'Life Buoy', Icon: LifeBuoy },
  { name: 'Lightbulb', label: 'Lightbulb', Icon: Lightbulb },
  { name: 'LineChart', label: 'Line Chart', Icon: LineChart },
  { name: 'Link', label: 'Link', Icon: Link },
  { name: 'Link2', label: 'Link 2', Icon: Link2 },
  { name: 'Linkedin', label: 'Linkedin', Icon: Linkedin },
  { name: 'List', label: 'List', Icon: List },
  { name: 'ListChecks', label: 'List Checks', Icon: ListChecks },
  { name: 'ListOrdered', label: 'List Ordered', Icon: ListOrdered },
  { name: 'ListTodo', label: 'List Todo', Icon: ListTodo },
  { name: 'ListTree', label: 'List Tree', Icon: ListTree },
  { name: 'Lock', label: 'Lock', Icon: Lock },
  { name: 'LockOpen', label: 'Lock Open', Icon: LockOpen },
  { name: 'Lollipop', label: 'Lollipop', Icon: Lollipop },
  { name: 'Magnet', label: 'Magnet', Icon: Magnet },
  { name: 'Mail', label: 'Mail', Icon: Mail },
  { name: 'Map', label: 'Map', Icon: Map },
  { name: 'MapPin', label: 'Map Pin', Icon: MapPin },
  { name: 'MapPinned', label: 'Map Pinned', Icon: MapPinned },
  { name: 'Martini', label: 'Martini', Icon: Martini },
  { name: 'Medal', label: 'Medal', Icon: Medal },
  { name: 'Megaphone', label: 'Megaphone', Icon: Megaphone },
  { name: 'MessageSquare', label: 'Message Square', Icon: MessageSquare },
  { name: 'Mic', label: 'Mic', Icon: Mic },
  { name: 'MicOff', label: 'Mic Off', Icon: MicOff },
  { name: 'Microscope', label: 'Microscope', Icon: Microscope },
  { name: 'Milestone', label: 'Milestone', Icon: Milestone },
  { name: 'Milk', label: 'Milk', Icon: Milk },
  { name: 'Monitor', label: 'Monitor', Icon: Monitor },
  { name: 'MonitorDot', label: 'Monitor Dot', Icon: MonitorDot },
  { name: 'MonitorPlay', label: 'Monitor Play', Icon: MonitorPlay },
  { name: 'Moon', label: 'Moon', Icon: Moon },
  { name: 'MountainSnow', label: 'Mountain Snow', Icon: MountainSnow },
  { name: 'Mouse', label: 'Mouse', Icon: Mouse },
  { name: 'Music', label: 'Music', Icon: Music },
  { name: 'Music2', label: 'Music 2', Icon: Music2 },
  { name: 'Music3', label: 'Music 3', Icon: Music3 },
  { name: 'Network', label: 'Network', Icon: Network },
  { name: 'Newspaper', label: 'Newspaper', Icon: Newspaper },
  { name: 'Notebook', label: 'Notebook', Icon: Notebook },
  { name: 'NotepadText', label: 'Notepad Text', Icon: NotepadText },
  { name: 'Nut', label: 'Nut', Icon: Nut },
  { name: 'OctagonAlert', label: 'Octagon Alert', Icon: OctagonAlert },
  { name: 'Package2', label: 'Package 2', Icon: Package2 },
  { name: 'PackageCheck', label: 'Package Check', Icon: PackageCheck },
  { name: 'PackageOpen', label: 'Package Open', Icon: PackageOpen },
  { name: 'PackagePlus', label: 'Package Plus', Icon: PackagePlus },
  { name: 'Paintbrush', label: 'Paintbrush', Icon: Paintbrush },
  { name: 'Palette', label: 'Palette', Icon: Palette },
  { name: 'PartyPopper', label: 'Party Popper', Icon: PartyPopper },
  { name: 'PawPrint', label: 'Paw Print', Icon: PawPrint },
  { name: 'PcCase', label: 'Pc Case', Icon: PcCase },
  { name: 'PenLine', label: 'Pen Line', Icon: PenLine },
  { name: 'PencilLine', label: 'Pencil Line', Icon: PencilLine },
  { name: 'Percent', label: 'Percent', Icon: Percent },
  { name: 'Phone', label: 'Phone', Icon: Phone },
  { name: 'PhoneCall', label: 'Phone Call', Icon: PhoneCall },
  { name: 'Piano', label: 'Piano', Icon: Piano },
  { name: 'Pickaxe', label: 'Pickaxe', Icon: Pickaxe },
  { name: 'PictureInPicture2', label: 'Picture In Picture 2', Icon: PictureInPicture2 },
  { name: 'PiggyBank', label: 'Piggy Bank', Icon: PiggyBank },
  { name: 'Pill', label: 'Pill', Icon: Pill },
  { name: 'Pin', label: 'Pin', Icon: Pin },
  { name: 'Pizza', label: 'Pizza', Icon: Pizza },
  { name: 'Plane', label: 'Plane', Icon: Plane },
  { name: 'Plug2', label: 'Plug 2', Icon: Plug2 },
  { name: 'Podcast', label: 'Podcast', Icon: Podcast },
  { name: 'Power', label: 'Power', Icon: Power },
  { name: 'Printer', label: 'Printer', Icon: Printer },
  { name: 'Projector', label: 'Projector', Icon: Projector },
  { name: 'Puzzle', label: 'Puzzle', Icon: Puzzle },
  { name: 'QrCode', label: 'Qr Code', Icon: QrCode },
  { name: 'Quote', label: 'Quote', Icon: Quote },
  { name: 'Rabbit', label: 'Rabbit', Icon: Rabbit },
  { name: 'Radar', label: 'Radar', Icon: Radar },
  { name: 'Radio', label: 'Radio', Icon: Radio },
  { name: 'Receipt', label: 'Receipt', Icon: Receipt },
  { name: 'Recycle', label: 'Recycle', Icon: Recycle },
  { name: 'Refrigerator', label: 'Refrigerator', Icon: Refrigerator },
  { name: 'Regex', label: 'Regex', Icon: Regex },
  { name: 'Rocket', label: 'Rocket', Icon: Rocket },
  { name: 'Router', label: 'Router', Icon: Router },
  { name: 'Rss', label: 'Rss', Icon: Rss },
  { name: 'Ruler', label: 'Ruler', Icon: Ruler },
  { name: 'Sailboat', label: 'Sailboat', Icon: Sailboat },
  { name: 'Sandwich', label: 'Sandwich', Icon: Sandwich },
  { name: 'Satellite', label: 'Satellite', Icon: Satellite },
  { name: 'SatelliteDish', label: 'Satellite Dish', Icon: SatelliteDish },
  { name: 'SaveAll', label: 'Save All', Icon: SaveAll },
  { name: 'Scale3d', label: 'Scale 3 d', Icon: Scale3d },
  { name: 'School', label: 'School', Icon: School },
  { name: 'Scissors', label: 'Scissors', Icon: Scissors },
  { name: 'ScrollText', label: 'Scroll Text', Icon: ScrollText },
  { name: 'Search', label: 'Search', Icon: Search },
  { name: 'SearchX', label: 'Search X', Icon: SearchX },
  { name: 'Send', label: 'Send', Icon: Send },
  { name: 'Server', label: 'Server', Icon: Server },
  { name: 'ServerCog', label: 'Server Cog', Icon: ServerCog },
  { name: 'ServerCrash', label: 'Server Crash', Icon: ServerCrash },
  { name: 'Settings', label: 'Settings', Icon: Settings },
  { name: 'Shapes', label: 'Shapes', Icon: Shapes },
  { name: 'Share2', label: 'Share 2', Icon: Share2 },
  { name: 'Sheet', label: 'Sheet', Icon: Sheet },
  { name: 'Shield', label: 'Shield', Icon: Shield },
  { name: 'ShieldAlert', label: 'Shield Alert', Icon: ShieldAlert },
  { name: 'ShieldCheck', label: 'Shield Check', Icon: ShieldCheck },
  { name: 'Ship', label: 'Ship', Icon: Ship },
  { name: 'ShoppingBag', label: 'Shopping Bag', Icon: ShoppingBag },
  { name: 'ShoppingBasket', label: 'Shopping Basket', Icon: ShoppingBasket },
  { name: 'ShoppingCart', label: 'Shopping Cart', Icon: ShoppingCart },
  { name: 'Shovel', label: 'Shovel', Icon: Shovel },
  { name: 'Smartphone', label: 'Smartphone', Icon: Smartphone },
  { name: 'SmartphoneCharging', label: 'Smartphone Charging', Icon: SmartphoneCharging },
  { name: 'SmilePlus', label: 'Smile Plus', Icon: SmilePlus },
  { name: 'Snowflake', label: 'Snowflake', Icon: Snowflake },
  { name: 'Sofa', label: 'Sofa', Icon: Sofa },
  { name: 'Soup', label: 'Soup', Icon: Soup },
  { name: 'Sparkle', label: 'Sparkle', Icon: Sparkle },
  { name: 'Sparkles', label: 'Sparkles', Icon: Sparkles },
  { name: 'Speaker', label: 'Speaker', Icon: Speaker },
  { name: 'Spline', label: 'Spline', Icon: Spline },
  { name: 'Sprout', label: 'Sprout', Icon: Sprout },
  { name: 'SquarePen', label: 'Square Pen', Icon: SquarePen },
  { name: 'SquareStack', label: 'Square Stack', Icon: SquareStack },
  { name: 'Stamp', label: 'Stamp', Icon: Stamp },
  { name: 'Star', label: 'Star', Icon: Star },
  { name: 'StarHalf', label: 'Star Half', Icon: StarHalf },
  { name: 'Stethoscope', label: 'Stethoscope', Icon: Stethoscope },
  { name: 'StickyNote', label: 'Sticky Note', Icon: StickyNote },
  { name: 'Store', label: 'Store', Icon: Store },
  { name: 'SunMedium', label: 'Sun Medium', Icon: SunMedium },
  { name: 'SunSnow', label: 'Sun Snow', Icon: SunSnow },
  { name: 'Swords', label: 'Swords', Icon: Swords },
  { name: 'Syringe', label: 'Syringe', Icon: Syringe },
  { name: 'Table2', label: 'Table 2', Icon: Table2 },
  { name: 'Tablet', label: 'Tablet', Icon: Tablet },
  { name: 'TabletSmartphone', label: 'Tablet Smartphone', Icon: TabletSmartphone },
  { name: 'Tag', label: 'Tag', Icon: Tag },
  { name: 'Tags', label: 'Tags', Icon: Tags },
  { name: 'Target', label: 'Target', Icon: Target },
  { name: 'Telescope', label: 'Telescope', Icon: Telescope },
  { name: 'Tent', label: 'Tent', Icon: Tent },
  { name: 'Terminal', label: 'Terminal', Icon: Terminal },
  { name: 'ThermometerSun', label: 'Thermometer Sun', Icon: ThermometerSun },
  { name: 'Ticket', label: 'Ticket', Icon: Ticket },
  { name: 'Timer', label: 'Timer', Icon: Timer },
  { name: 'TrainFront', label: 'Train Front', Icon: TrainFront },
  { name: 'Trash', label: 'Trash', Icon: Trash },
  { name: 'Trees', label: 'Trees', Icon: Trees },
  { name: 'TrendingUp', label: 'Trending Up', Icon: TrendingUp },
  { name: 'Trophy', label: 'Trophy', Icon: Trophy },
  { name: 'Truck', label: 'Truck', Icon: Truck },
  { name: 'Tv', label: 'Tv', Icon: Tv },
  { name: 'TvMinimal', label: 'Tv Minimal', Icon: TvMinimal },
  { name: 'Umbrella', label: 'Umbrella', Icon: Umbrella },
  { name: 'Underline', label: 'Underline', Icon: Underline },
  { name: 'Unlock', label: 'Unlock', Icon: Unlock },
  { name: 'Upload', label: 'Upload', Icon: Upload },
  { name: 'Usb', label: 'Usb', Icon: Usb },
  { name: 'User', label: 'User', Icon: User },
  { name: 'UserPlus', label: 'User Plus', Icon: UserPlus },
  { name: 'UserRound', label: 'User Round', Icon: UserRound },
  { name: 'UserRoundCheck', label: 'User Round Check', Icon: UserRoundCheck },
  { name: 'Users', label: 'Users', Icon: Users },
  { name: 'UsersRound', label: 'Users Round', Icon: UsersRound },
  { name: 'Utensils', label: 'Utensils', Icon: Utensils },
  { name: 'Video', label: 'Video', Icon: Video },
  { name: 'VideoOff', label: 'Video Off', Icon: VideoOff },
  { name: 'Voicemail', label: 'Voicemail', Icon: Voicemail },
  { name: 'Volume2', label: 'Volume 2', Icon: Volume2 },
  { name: 'Wallet', label: 'Wallet', Icon: Wallet },
  { name: 'Wand2', label: 'Wand 2', Icon: Wand2 },
  { name: 'Warehouse', label: 'Warehouse', Icon: Warehouse },
  { name: 'Watch', label: 'Watch', Icon: Watch },
  { name: 'Waves', label: 'Waves', Icon: Waves },
  { name: 'Webcam', label: 'Webcam', Icon: Webcam },
  { name: 'Wheat', label: 'Wheat', Icon: Wheat },
  { name: 'Wind', label: 'Wind', Icon: Wind },
  { name: 'Wine', label: 'Wine', Icon: Wine },
  { name: 'Workflow', label: 'Workflow', Icon: Workflow },
  { name: 'Wrench', label: 'Wrench', Icon: Wrench },
  { name: 'Youtube', label: 'Youtube', Icon: Youtube },
  { name: 'Zap', label: 'Zap', Icon: Zap },
  { name: 'ZapOff', label: 'Zap Off', Icon: ZapOff },
  { name: 'ZoomIn', label: 'Zoom In', Icon: ZoomIn },
  { name: 'ZoomOut', label: 'Zoom Out', Icon: ZoomOut },
] as const;

export const LUCIDE_ICONS_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  COLLECTION_LUCIDE_OPTIONS.map((o) => [o.name, o.Icon])
);

