import type { LucideIcon } from 'lucide-react';
import {
  Archive,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  CalendarDays,
  ClipboardList,
  Clock,
  Code2,
  Database,
  FileText,
  Flag,
  Folder,
  FolderKanban,
  FolderOpen,
  Globe,
  Hash,
  Heart,
  Home,
  Image,
  Inbox,
  Kanban,
  Key,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link2,
  List,
  ListTodo,
  Mail,
  MapPin,
  MessageSquare,
  Music,
  Pin,
  Puzzle,
  Settings,
  Shield,
  Sparkles,
  Star,
  Table2,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  User,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

export type CollectionLucideOption = { name: string; label: string; Icon: LucideIcon };

/** Curated Lucide icons for collections (name = lucide-react export). */
export const COLLECTION_LUCIDE_OPTIONS: readonly CollectionLucideOption[] = [
  { name: 'Table2', label: 'Table', Icon: Table2 },
  { name: 'Folder', label: 'Folder', Icon: Folder },
  { name: 'FolderOpen', label: 'Open folder', Icon: FolderOpen },
  { name: 'FolderKanban', label: 'Kanban folder', Icon: FolderKanban },
  { name: 'Kanban', label: 'Kanban', Icon: Kanban },
  { name: 'LayoutGrid', label: 'Grid', Icon: LayoutGrid },
  { name: 'List', label: 'List', Icon: List },
  { name: 'ListTodo', label: 'Todo list', Icon: ListTodo },
  { name: 'BookOpen', label: 'Book', Icon: BookOpen },
  { name: 'FileText', label: 'Document', Icon: FileText },
  { name: 'ClipboardList', label: 'Checklist', Icon: ClipboardList },
  { name: 'CalendarDays', label: 'Calendar', Icon: CalendarDays },
  { name: 'Clock', label: 'Clock', Icon: Clock },
  { name: 'Inbox', label: 'Inbox', Icon: Inbox },
  { name: 'Mail', label: 'Mail', Icon: Mail },
  { name: 'MessageSquare', label: 'Chat', Icon: MessageSquare },
  { name: 'Archive', label: 'Archive', Icon: Archive },
  { name: 'Box', label: 'Box', Icon: Box },
  { name: 'Database', label: 'Database', Icon: Database },
  { name: 'BarChart3', label: 'Chart', Icon: BarChart3 },
  { name: 'TrendingUp', label: 'Trending', Icon: TrendingUp },
  { name: 'Tag', label: 'Tag', Icon: Tag },
  { name: 'Hash', label: 'Hash', Icon: Hash },
  { name: 'Layers', label: 'Layers', Icon: Layers },
  { name: 'Pin', label: 'Pin', Icon: Pin },
  { name: 'Link2', label: 'Link', Icon: Link2 },
  { name: 'Briefcase', label: 'Work', Icon: Briefcase },
  { name: 'Building2', label: 'Building', Icon: Building2 },
  { name: 'Home', label: 'Home', Icon: Home },
  { name: 'Globe', label: 'Globe', Icon: Globe },
  { name: 'MapPin', label: 'Location', Icon: MapPin },
  { name: 'Flag', label: 'Flag', Icon: Flag },
  { name: 'User', label: 'User', Icon: User },
  { name: 'Users', label: 'People', Icon: Users },
  { name: 'Star', label: 'Star', Icon: Star },
  { name: 'Heart', label: 'Heart', Icon: Heart },
  { name: 'Trophy', label: 'Trophy', Icon: Trophy },
  { name: 'Target', label: 'Target', Icon: Target },
  { name: 'Zap', label: 'Zap', Icon: Zap },
  { name: 'Sparkles', label: 'Sparkles', Icon: Sparkles },
  { name: 'Lightbulb', label: 'Idea', Icon: Lightbulb },
  { name: 'Key', label: 'Key', Icon: Key },
  { name: 'Shield', label: 'Shield', Icon: Shield },
  { name: 'Wrench', label: 'Tools', Icon: Wrench },
  { name: 'Settings', label: 'Settings', Icon: Settings },
  { name: 'Puzzle', label: 'Puzzle', Icon: Puzzle },
  { name: 'Code2', label: 'Code', Icon: Code2 },
  { name: 'Image', label: 'Image', Icon: Image },
  { name: 'Music', label: 'Music', Icon: Music },
  { name: 'Bell', label: 'Bell', Icon: Bell },
] as const;

export const LUCIDE_ICONS_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  COLLECTION_LUCIDE_OPTIONS.map((o) => [o.name, o.Icon])
);
