/** Searchable preset emojis for collection icons (`q` = lowercase keywords, space-separated). */
export type CollectionEmojiOption = {
  emoji: string;
  /** Lowercase search tokens (name, category, synonyms). */
  q: string;
};

export const COLLECTION_EMOJI_OPTIONS: readonly CollectionEmojiOption[] = [
  { emoji: '📦', q: 'package box shipping delivery archive' },
  { emoji: '📁', q: 'folder file directory' },
  { emoji: '📂', q: 'folder open files' },
  { emoji: '🗂️', q: 'divider index organize' },
  { emoji: '📋', q: 'clipboard list tasks' },
  { emoji: '📊', q: 'chart bar graph analytics stats' },
  { emoji: '📈', q: 'trending up growth chart' },
  { emoji: '📉', q: 'down decline chart' },
  { emoji: '🎯', q: 'target goal dart focus' },
  { emoji: '✅', q: 'check done complete yes' },
  { emoji: '☑️', q: 'checkbox ballot vote' },
  { emoji: '✔️', q: 'check mark tick' },
  { emoji: '⭐', q: 'star favorite rating' },
  { emoji: '🌟', q: 'star sparkle glow' },
  { emoji: '💫', q: 'dizzy star spark' },
  { emoji: '✨', q: 'sparkles magic new' },
  { emoji: '💡', q: 'lightbulb idea insight tip' },
  { emoji: '🔦', q: 'flashlight torch light' },
  { emoji: '🏠', q: 'home house' },
  { emoji: '🏡', q: 'house garden home' },
  { emoji: '🏢', q: 'office building work company' },
  { emoji: '🏗️', q: 'construction building crane' },
  { emoji: '📝', q: 'memo note pencil write' },
  { emoji: '📄', q: 'page document' },
  { emoji: '📃', q: 'page curl document' },
  { emoji: '📑', q: 'bookmark tabs' },
  { emoji: '📅', q: 'calendar date schedule' },
  { emoji: '🗓️', q: 'spiral calendar schedule' },
  { emoji: '📆', q: 'tear calendar' },
  { emoji: '🕐', q: 'clock time one' },
  { emoji: '⏰', q: 'alarm clock morning' },
  { emoji: '⏱️', q: 'stopwatch timer' },
  { emoji: '⏲️', q: 'timer hourglass' },
  { emoji: '🔥', q: 'fire hot trending lit' },
  { emoji: '💼', q: 'briefcase work business' },
  { emoji: '🎨', q: 'art palette design paint' },
  { emoji: '🖌️', q: 'brush paint art' },
  { emoji: '🖍️', q: 'crayon draw' },
  { emoji: '🚀', q: 'rocket launch ship fast startup' },
  { emoji: '🛸', q: 'ufo flying saucer' },
  { emoji: '🛰️', q: 'satellite space' },
  { emoji: '📌', q: 'pin pushpin attach' },
  { emoji: '📍', q: 'round pin location map' },
  { emoji: '🛠️', q: 'hammer wrench tools fix build' },
  { emoji: '🔧', q: 'wrench tool settings' },
  { emoji: '🔨', q: 'hammer build' },
  { emoji: '⚙️', q: 'gear cog settings machine' },
  { emoji: '🧰', q: 'toolbox tools' },
  { emoji: '📎', q: 'paperclip attach' },
  { emoji: '🖇️', q: 'paperclips link' },
  { emoji: '💬', q: 'speech bubble chat comment message' },
  { emoji: '💭', q: 'thought balloon idea' },
  { emoji: '🗨️', q: 'left speech' },
  { emoji: '👋', q: 'wave hello hand hi' },
  { emoji: '👍', q: 'thumbs up like yes good' },
  { emoji: '👎', q: 'thumbs down no' },
  { emoji: '👏', q: 'clap applause celebrate' },
  { emoji: '🙌', q: 'raised hands celebrate' },
  { emoji: '🤝', q: 'handshake deal agreement' },
  { emoji: '✍️', q: 'writing hand sign' },
  { emoji: '🔔', q: 'bell notification alert' },
  { emoji: '🔕', q: 'bell slash mute silent' },
  { emoji: '📣', q: 'megaphone announce marketing' },
  { emoji: '📢', q: 'loudspeaker announce' },
  { emoji: '🔑', q: 'key lock access password' },
  { emoji: '🗝️', q: 'old key vintage' },
  { emoji: '🔐', q: 'closed lock key secure' },
  { emoji: '🔒', q: 'lock secure private' },
  { emoji: '🔓', q: 'unlock open' },
  { emoji: '🌍', q: 'earth globe europe africa world' },
  { emoji: '🌎', q: 'earth americas globe world' },
  { emoji: '🌏', q: 'earth asia australia globe' },
  { emoji: '🗺️', q: 'map world travel' },
  { emoji: '🧭', q: 'compass navigate direction' },
  { emoji: '❤️', q: 'heart love red like' },
  { emoji: '🧡', q: 'orange heart' },
  { emoji: '💛', q: 'yellow heart' },
  { emoji: '💚', q: 'green heart' },
  { emoji: '💙', q: 'blue heart' },
  { emoji: '💜', q: 'purple heart' },
  { emoji: '🖤', q: 'black heart' },
  { emoji: '🤍', q: 'white heart' },
  { emoji: '💔', q: 'broken heart sad' },
  { emoji: '❣️', q: 'heart exclamation' },
  { emoji: '💕', q: 'two hearts love' },
  { emoji: '💞', q: 'revolving hearts' },
  { emoji: '💓', q: 'beating heart' },
  { emoji: '💗', q: 'growing heart' },
  { emoji: '🎵', q: 'music note song audio' },
  { emoji: '🎶', q: 'music notes songs' },
  { emoji: '🎤', q: 'microphone karaoke podcast' },
  { emoji: '🎧', q: 'headphones listen audio' },
  { emoji: '🎸', q: 'guitar rock music' },
  { emoji: '🎹', q: 'piano keyboard music' },
  { emoji: '🥁', q: 'drum music beat' },
  { emoji: '🎬', q: 'clapper film movie video' },
  { emoji: '🎥', q: 'movie camera film' },
  { emoji: '📹', q: 'video camera record' },
  { emoji: '📷', q: 'camera photo' },
  { emoji: '📸', q: 'camera flash photo' },
  { emoji: '🖼️', q: 'frame picture art' },
  { emoji: '🎭', q: 'theater drama masks acting' },
  { emoji: '🎪', q: 'circus tent event' },
  { emoji: '🎉', q: 'party popper celebrate confetti' },
  { emoji: '🎊', q: 'confetti ball celebrate' },
  { emoji: '🎁', q: 'gift present box' },
  { emoji: '🏷️', q: 'label tag price' },
  { emoji: '🔖', q: 'bookmark save' },
  { emoji: '🧠', q: 'brain think mind ai' },
  { emoji: '👁️', q: 'eye watch vision' },
  { emoji: '👀', q: 'eyes look see' },
  { emoji: '⚡', q: 'lightning zap fast energy power' },
  { emoji: '☀️', q: 'sun sunny weather day' },
  { emoji: '🌤️', q: 'sun cloud weather' },
  { emoji: '⛅', q: 'cloud sun weather' },
  { emoji: '☁️', q: 'cloud weather sky' },
  { emoji: '🌧️', q: 'rain cloud weather' },
  { emoji: '⛈️', q: 'storm thunder rain' },
  { emoji: '❄️', q: 'snowflake winter cold' },
  { emoji: '☃️', q: 'snowman winter' },
  { emoji: '🌈', q: 'rainbow pride color spectrum' },
  { emoji: '🌊', q: 'wave ocean water sea' },
  { emoji: '💧', q: 'droplet water liquid' },
  { emoji: '🌿', q: 'herb leaf plant nature green' },
  { emoji: '🍀', q: 'clover luck four leaf' },
  { emoji: '🌱', q: 'seedling plant grow startup' },
  { emoji: '🌲', q: 'evergreen tree forest pine' },
  { emoji: '🌳', q: 'deciduous tree park' },
  { emoji: '🌴', q: 'palm tree tropical vacation' },
  { emoji: '🌵', q: 'cactus desert plant' },
  { emoji: '🌻', q: 'sunflower flower summer' },
  { emoji: '🌹', q: 'rose flower love' },
  { emoji: '🌷', q: 'tulip flower spring' },
  { emoji: '🌼', q: 'blossom flower' },
  { emoji: '🐝', q: 'bee honey insect kern buzz' },
  { emoji: '🍯', q: 'honey pot sweet' },
  { emoji: '🦋', q: 'butterfly insect nature' },
  { emoji: '🐛', q: 'bug caterpillar insect' },
  { emoji: '🐞', q: 'ladybug beetle insect' },
  { emoji: '🐢', q: 'turtle slow steady' },
  { emoji: '🐙', q: 'octopus sea creature' },
  { emoji: '🐬', q: 'dolphin ocean' },
  { emoji: '🐳', q: 'whale ocean' },
  { emoji: '🐶', q: 'dog puppy pet' },
  { emoji: '🐱', q: 'cat kitten pet' },
  { emoji: '🐭', q: 'mouse rodent' },
  { emoji: '🐰', q: 'rabbit bunny easter' },
  { emoji: '🦊', q: 'fox clever' },
  { emoji: '🐻', q: 'bear animal' },
  { emoji: '🐼', q: 'panda cute' },
  { emoji: '🦁', q: 'lion brave king' },
  { emoji: '🐮', q: 'cow farm' },
  { emoji: '🐷', q: 'pig farm' },
  { emoji: '🐸', q: 'frog green' },
  { emoji: '🦄', q: 'unicorn magic startup rare' },
  { emoji: '🐔', q: 'chicken farm' },
  { emoji: '🐧', q: 'penguin cold cute' },
  { emoji: '🐦', q: 'bird fly tweet' },
  { emoji: '🦅', q: 'eagle america fly' },
  { emoji: '🦉', q: 'owl wise night' },
  { emoji: '🦇', q: 'bat halloween night' },
  { emoji: '🐴', q: 'horse ride' },
  { emoji: '🦌', q: 'deer forest' },
  { emoji: '🐍', q: 'snake reptile' },
  { emoji: '🐲', q: 'dragon myth' },
  { emoji: '🦕', q: 'sauropod dinosaur' },
  { emoji: '🦖', q: 't-rex dinosaur' },
  { emoji: '🦀', q: 'crab seafood' },
  { emoji: '🦞', q: 'lobster seafood' },
  { emoji: '🐟', q: 'fish swim' },
  { emoji: '🐠', q: 'tropical fish' },
  { emoji: '🐡', q: 'blowfish fish' },
  { emoji: '🦈', q: 'shark ocean danger' },
  { emoji: '🍎', q: 'apple red fruit health' },
  { emoji: '🍏', q: 'green apple fruit' },
  { emoji: '🍊', q: 'orange fruit citrus' },
  { emoji: '🍋', q: 'lemon citrus sour' },
  { emoji: '🍌', q: 'banana fruit' },
  { emoji: '🍉', q: 'watermelon fruit summer' },
  { emoji: '🍇', q: 'grapes fruit wine' },
  { emoji: '🍓', q: 'strawberry berry fruit' },
  { emoji: '🫐', q: 'blueberries fruit' },
  { emoji: '🍒', q: 'cherries fruit' },
  { emoji: '🍑', q: 'peach fruit' },
  { emoji: '🥝', q: 'kiwi fruit' },
  { emoji: '🍍', q: 'pineapple tropical' },
  { emoji: '🥥', q: 'coconut tropical' },
  { emoji: '🥑', q: 'avocado healthy' },
  { emoji: '🍅', q: 'tomato vegetable' },
  { emoji: '🥕', q: 'carrot vegetable' },
  { emoji: '🌽', q: 'corn vegetable' },
  { emoji: '🥦', q: 'broccoli vegetable health' },
  { emoji: '🍞', q: 'bread bakery' },
  { emoji: '🥐', q: 'croissant pastry breakfast' },
  { emoji: '🥖', q: 'baguette bread' },
  { emoji: '🥨', q: 'pretzel snack' },
  { emoji: '🧀', q: 'cheese dairy' },
  { emoji: '🍖', q: 'meat bone food' },
  { emoji: '🍗', q: 'chicken leg food' },
  { emoji: '🥩', q: 'steak meat' },
  { emoji: '🥓', q: 'bacon breakfast' },
  { emoji: '🍔', q: 'burger hamburger fast food' },
  { emoji: '🍟', q: 'fries fast food' },
  { emoji: '🍕', q: 'pizza slice food' },
  { emoji: '🌭', q: 'hot dog food' },
  { emoji: '🌮', q: 'taco mexican food' },
  { emoji: '🌯', q: 'burrito mexican food' },
  { emoji: '🥗', q: 'salad healthy green' },
  { emoji: '🍝', q: 'spaghetti pasta italian' },
  { emoji: '🍜', q: 'ramen noodles soup' },
  { emoji: '🍲', q: 'stew pot food' },
  { emoji: '🍛', q: 'curry rice food' },
  { emoji: '🍣', q: 'sushi japanese fish' },
  { emoji: '🍱', q: 'bento box japanese' },
  { emoji: '🍙', q: 'rice ball japanese' },
  { emoji: '🍚', q: 'cooked rice' },
  { emoji: '🍘', q: 'rice cracker' },
  { emoji: '🍥', q: 'fish cake swirl' },
  { emoji: '🥮', q: 'moon cake' },
  { emoji: '🍢', q: 'oden skewer' },
  { emoji: '🍡', q: 'dango dessert' },
  { emoji: '🍧', q: 'shaved ice dessert cold' },
  { emoji: '🍨', q: 'ice cream dessert' },
  { emoji: '🍦', q: 'soft ice cream dessert' },
  { emoji: '🧁', q: 'cupcake dessert sweet' },
  { emoji: '🍰', q: 'cake dessert birthday' },
  { emoji: '🎂', q: 'birthday cake party' },
  { emoji: '🍪', q: 'cookie dessert' },
  { emoji: '🍫', q: 'chocolate bar candy' },
  { emoji: '🍬', q: 'candy sweet' },
  { emoji: '🍭', q: 'lollipop candy sweet' },
  { emoji: '🍮', q: 'custard dessert' },
  { emoji: '☕', q: 'coffee cafe hot drink caffeine' },
  { emoji: '🍵', q: 'tea matcha drink' },
  { emoji: '🧃', q: 'juice box drink' },
  { emoji: '🥤', q: 'cup straw soda drink' },
  { emoji: '🧋', q: 'bubble tea boba' },
  { emoji: '🍶', q: 'sake bottle japanese' },
  { emoji: '🍺', q: 'beer mug drink cheers' },
  { emoji: '🍻', q: 'clinking beer cheers party' },
  { emoji: '🥂', q: 'champagne clink celebrate toast' },
  { emoji: '🍷', q: 'wine glass drink' },
  { emoji: '🥃', q: 'whiskey tumbler drink' },
  { emoji: '🍸', q: 'cocktail martini drink' },
  { emoji: '🍹', q: 'tropical drink cocktail' },
  { emoji: '🧊', q: 'ice cube cold' },
  { emoji: '⚽', q: 'soccer football ball sport' },
  { emoji: '🏀', q: 'basketball ball sport' },
  { emoji: '🏈', q: 'american football sport' },
  { emoji: '⚾', q: 'baseball ball sport' },
  { emoji: '🥎', q: 'softball sport' },
  { emoji: '🎾', q: 'tennis sport' },
  { emoji: '🏐', q: 'volleyball sport' },
  { emoji: '🏉', q: 'rugby sport' },
  { emoji: '🎱', q: '8 ball pool billiards' },
  { emoji: '🪀', q: 'yo-yo toy' },
  { emoji: '🏓', q: 'ping pong paddle' },
  { emoji: '🏸', q: 'badminton racket' },
  { emoji: '🥅', q: 'goal net sport' },
  { emoji: '⛳', q: 'golf flag hole' },
  { emoji: '⛷️', q: 'skier ski snow' },
  { emoji: '🏂', q: 'snowboard winter' },
  { emoji: '🏋️', q: 'weight lift gym fitness' },
  { emoji: '🤸', q: 'cartwheel gymnastics' },
  { emoji: '⛹️', q: 'basketball person sport' },
  { emoji: '🤺', q: 'fencing sword sport' },
  { emoji: '🤾', q: 'handball sport' },
  { emoji: '🏌️', q: 'golfer golf' },
  { emoji: '🏇', q: 'horse racing' },
  { emoji: '🧘', q: 'yoga meditation zen' },
  { emoji: '🏄', q: 'surfing wave ocean' },
  { emoji: '🏊', q: 'swimming pool swim' },
  { emoji: '🚴', q: 'biking bicycle cycling' },
  { emoji: '🚵', q: 'mountain bike cycling' },
  { emoji: '🎿', q: 'skis winter snow' },
  { emoji: '⛸️', q: 'ice skate winter' },
  { emoji: '🥇', q: 'gold medal first place win' },
  { emoji: '🥈', q: 'silver medal second' },
  { emoji: '🥉', q: 'bronze medal third' },
  { emoji: '🏆', q: 'trophy winner championship' },
  { emoji: '🏅', q: 'sports medal award' },
  { emoji: '🎖️', q: 'military medal honor' },
  { emoji: '🎗️', q: 'reminder ribbon cause' },
  { emoji: '🎫', q: 'ticket admission event' },
  { emoji: '🎟️', q: 'admission tickets' },
  { emoji: '🤹', q: 'juggling circus skill' },
  { emoji: '🩰', q: 'ballet shoes dance' },
  { emoji: '🧵', q: 'thread sewing craft' },
  { emoji: '🧶', q: 'yarn knitting craft' },
  { emoji: '🪡', q: 'needle sewing' },
  { emoji: '🪢', q: 'knot rope' },
  { emoji: '👓', q: 'glasses eyewear read' },
  { emoji: '🕶️', q: 'sunglasses cool shades' },
  { emoji: '🥽', q: 'goggles lab swim safety' },
  { emoji: '🥼', q: 'lab coat science doctor' },
  { emoji: '🦺', q: 'safety vest construction' },
  { emoji: '👔', q: 'necktie business formal' },
  { emoji: '👕', q: 'shirt clothes casual' },
  { emoji: '👖', q: 'jeans pants clothes' },
  { emoji: '🧣', q: 'scarf winter warm' },
  { emoji: '🧤', q: 'gloves winter hands' },
  { emoji: '🧥', q: 'coat jacket winter' },
  { emoji: '🧦', q: 'socks clothes' },
  { emoji: '👗', q: 'dress clothes' },
  { emoji: '👘', q: 'kimono japanese' },
  { emoji: '🥻', q: 'sari clothes' },
  { emoji: '🩱', q: 'one-piece swimsuit' },
  { emoji: '🩲', q: 'swim brief' },
  { emoji: '🩳', q: 'shorts summer' },
  { emoji: '👙', q: 'bikini beach swim' },
  { emoji: '👚', q: 'woman clothes blouse' },
  { emoji: '👛', q: 'purse coin' },
  { emoji: '👜', q: 'handbag bag purse' },
  { emoji: '👝', q: 'clutch bag pouch' },
  { emoji: '🛍️', q: 'shopping bags retail' },
  { emoji: '🎒', q: 'backpack school travel bag' },
  { emoji: '👞', q: 'mans shoe dress' },
  { emoji: '👟', q: 'running shoe sneaker sport' },
  { emoji: '🥾', q: 'hiking boot outdoor' },
  { emoji: '🥿', q: 'flat shoe womans' },
  { emoji: '👠', q: 'high heel shoe' },
  { emoji: '👡', q: 'sandal womans shoe' },
  { emoji: '👢', q: 'boot shoe winter' },
  { emoji: '👑', q: 'crown king queen royal vip' },
  { emoji: '👒', q: 'hat womans' },
  { emoji: '🎩', q: 'top hat formal magic' },
  { emoji: '🎓', q: 'graduation cap education school' },
  { emoji: '🧢', q: 'billed cap hat baseball' },
  { emoji: '⛑️', q: 'rescue helmet safety' },
  { emoji: '📿', q: 'prayer beads meditation' },
  { emoji: '💄', q: 'lipstick makeup beauty' },
  { emoji: '💍', q: 'ring wedding jewelry' },
  { emoji: '💎', q: 'gem diamond jewel valuable' },
  { emoji: '🔇', q: 'muted speaker silent' },
  { emoji: '🔈', q: 'speaker low volume' },
  { emoji: '🔉', q: 'speaker medium volume' },
  { emoji: '🔊', q: 'speaker high volume loud' },
  { emoji: '📻', q: 'radio broadcast audio' },
  { emoji: '📱', q: 'mobile phone smartphone' },
  { emoji: '📲', q: 'mobile arrow call' },
  { emoji: '☎️', q: 'telephone phone classic' },
  { emoji: '📞', q: 'telephone receiver call' },
  { emoji: '📟', q: 'pager beeper old' },
  { emoji: '📠', q: 'fax machine office' },
  { emoji: '🔋', q: 'battery power energy' },
  { emoji: '🪫', q: 'low battery empty' },
  { emoji: '🔌', q: 'electric plug power cable' },
  { emoji: '💻', q: 'laptop computer work dev' },
  { emoji: '🖥️', q: 'desktop computer monitor' },
  { emoji: '🖨️', q: 'printer office paper' },
  { emoji: '⌨️', q: 'keyboard typing' },
  { emoji: '🖱️', q: 'computer mouse' },
  { emoji: '🖲️', q: 'trackball mouse' },
  { emoji: '💽', q: 'minidisc storage retro' },
  { emoji: '💾', q: 'floppy disk save retro' },
  { emoji: '💿', q: 'cd disc optical' },
  { emoji: '📀', q: 'dvd disc movie' },
  { emoji: '🧮', q: 'abacus math calculate' },
  { emoji: '🎰', q: 'slot machine casino luck' },
  { emoji: '🎮', q: 'video game controller play' },
  { emoji: '🕹️', q: 'joystick arcade game' },
  { emoji: '🎲', q: 'dice game random chance' },
  { emoji: '🧩', q: 'puzzle piece jigsaw solve' },
  { emoji: '🧸', q: 'teddy bear toy cute' },
  { emoji: '🪅', q: 'piñata party' },
  { emoji: '🪆', q: 'nesting dolls russian' },
  { emoji: '♠️', q: 'spade suit cards poker' },
  { emoji: '♥️', q: 'heart suit cards love' },
  { emoji: '♦️', q: 'diamond suit cards' },
  { emoji: '♣️', q: 'club suit cards' },
  { emoji: '♟️', q: 'chess pawn strategy game' },
  { emoji: '🃏', q: 'joker card wild' },
  { emoji: '🀄', q: 'mahjong red dragon game' },
  { emoji: '🎴', q: 'flower playing cards' },
  { emoji: '🌙', q: 'crescent moon night sleep' },
  { emoji: '🌛', q: 'moon face waxing' },
  { emoji: '🌜', q: 'moon face waning' },
  { emoji: '🌚', q: 'new moon face dark' },
  { emoji: '🌝', q: 'full moon face' },
  { emoji: '🌞', q: 'sun face bright happy' },
  { emoji: '🌠', q: 'shooting star wish' },
  { emoji: '🌌', q: 'milky way space galaxy' },
  { emoji: '☄️', q: 'comet space' },
  { emoji: '🪐', q: 'ringed planet saturn space' },
  { emoji: '🌑', q: 'new moon phase' },
  { emoji: '🌒', q: 'waxing moon' },
  { emoji: '🌓', q: 'first quarter moon' },
  { emoji: '🌔', q: 'waxing gibbous moon' },
  { emoji: '🌕', q: 'full moon' },
  { emoji: '🌖', q: 'waning gibbous moon' },
  { emoji: '🌗', q: 'last quarter moon' },
  { emoji: '🌘', q: 'waning moon' },
  { emoji: '🚗', q: 'car automobile drive transport' },
  { emoji: '🚕', q: 'taxi cab uber ride' },
  { emoji: '🚙', q: 'suv blue car' },
  { emoji: '🚌', q: 'bus public transport' },
  { emoji: '🚎', q: 'trolleybus tram' },
  { emoji: '🏎️', q: 'racing car fast f1' },
  { emoji: '🚓', q: 'police car emergency' },
  { emoji: '🚑', q: 'ambulance emergency medical' },
  { emoji: '🚒', q: 'fire engine truck' },
  { emoji: '🚐', q: 'minivan van' },
  { emoji: '🛻', q: 'pickup truck' },
  { emoji: '🚚', q: 'delivery truck logistics' },
  { emoji: '🚛', q: 'articulated lorry truck' },
  { emoji: '🚜', q: 'tractor farm' },
  { emoji: '🏍️', q: 'motorcycle bike' },
  { emoji: '🛵', q: 'motor scooter vespa' },
  { emoji: '🚲', q: 'bicycle bike cycle' },
  { emoji: '🛴', q: 'kick scooter' },
  { emoji: '🛹', q: 'skateboard' },
  { emoji: '🛼', q: 'roller skate' },
  { emoji: '🚁', q: 'helicopter fly' },
  { emoji: '✈️', q: 'airplane plane flight travel' },
  { emoji: '🛫', q: 'airplane departure takeoff' },
  { emoji: '🛬', q: 'airplane arrival landing' },
  { emoji: '🪂', q: 'parachute skydive' },
  { emoji: '💺', q: 'seat chair airplane' },
  { emoji: '🚢', q: 'ship cruise boat' },
  { emoji: '⛵', q: 'sailboat yacht' },
  { emoji: '🚤', q: 'speedboat boat fast' },
  { emoji: '🛥️', q: 'motor boat' },
  { emoji: '🛳️', q: 'passenger ship cruise' },
  { emoji: '⛴️', q: 'ferry boat transport' },
  { emoji: '🚉', q: 'train station railway' },
  { emoji: '🚊', q: 'tram railway' },
  { emoji: '🚝', q: 'monorail' },
  { emoji: '🚞', q: 'mountain railway' },
  { emoji: '🚋', q: 'tram car' },
  { emoji: '🚃', q: 'railway car train' },
  { emoji: '🚄', q: 'bullet train fast shinkansen' },
  { emoji: '🚅', q: 'bullet train nose' },
  { emoji: '🚈', q: 'light rail' },
  { emoji: '🚂', q: 'locomotive steam train' },
  { emoji: '🚆', q: 'train railway' },
  { emoji: '🚇', q: 'metro subway underground' },
  { emoji: '🎢', q: 'roller coaster fun park' },
  { emoji: '🎡', q: 'ferris wheel fair' },
  { emoji: '🎠', q: 'carousel horse fair' },
  { emoji: '⛲', q: 'fountain park water' },
  { emoji: '⛺', q: 'tent camping outdoor' },
  { emoji: '🌁', q: 'foggy bridge city' },
  { emoji: '🌃', q: 'night stars city' },
  { emoji: '🏙️', q: 'cityscape skyline urban' },
  { emoji: '🌄', q: 'sunrise mountains morning' },
  { emoji: '🌅', q: 'sunrise sea horizon' },
  { emoji: '🌆', q: 'city dusk sunset' },
  { emoji: '🌇', q: 'sunset buildings evening' },
  { emoji: '🌉', q: 'bridge night golden gate' },
  { emoji: '♨️', q: 'hotsprings onsen steam' },
  { emoji: '💹', q: 'chart yen market money' },
  { emoji: '💰', q: 'money bag dollar cash rich' },
  { emoji: '💴', q: 'yen banknote money japan' },
  { emoji: '💵', q: 'dollar banknote money usd' },
  { emoji: '💶', q: 'euro banknote money eur' },
  { emoji: '💷', q: 'pound banknote money gbp' },
  { emoji: '💸', q: 'money wings fly spend' },
  { emoji: '💳', q: 'credit card payment buy' },
  { emoji: '🧾', q: 'receipt bill expense' },
  { emoji: '⚖️', q: 'balance scale law justice fair' },
  { emoji: '🔫', q: 'water pistol toy gun' },
  { emoji: '🪃', q: 'boomerang return' },
  { emoji: '🏹', q: 'bow arrow archery target' },
  { emoji: '🛡️', q: 'shield defense security' },
  { emoji: '🪚', q: 'carpentry saw wood' },
  { emoji: '🔪', q: 'kitchen knife cook' },
  { emoji: '🗡️', q: 'dagger blade weapon' },
  { emoji: '⚔️', q: 'crossed swords battle fight' },
  { emoji: '🚬', q: 'cigarette smoke' },
  { emoji: '⚰️', q: 'coffin death dark' },
  { emoji: '🪦', q: 'headstone grave cemetery' },
  { emoji: '⚱️', q: 'funeral urn ashes' },
  { emoji: '🏺', q: 'amphora vase ancient' },
  { emoji: '🔮', q: 'crystal ball magic predict' },
  { emoji: '🧿', q: 'nazar evil eye charm' },
  { emoji: '💈', q: 'barber pole haircut' },
  { emoji: '⚗️', q: 'alembic chemistry distill' },
  { emoji: '🔭', q: 'telescope astronomy space look' },
  { emoji: '🔬', q: 'microscope science lab research' },
  { emoji: '🕳️', q: 'hole pit' },
  { emoji: '🩹', q: 'bandage adhesive heal' },
  { emoji: '🩺', q: 'stethoscope doctor health' },
  { emoji: '💊', q: 'pill medicine pharmacy health' },
  { emoji: '💉', q: 'syringe vaccine shot medical' },
  { emoji: '🧬', q: 'dna genetics science biology' },
  { emoji: '🦠', q: 'microbe virus germ biology' },
  { emoji: '🧪', q: 'test tube chemistry experiment' },
  { emoji: '🧫', q: 'petri dish culture lab' },
  { emoji: '🦷', q: 'tooth dentist dental' },
  { emoji: '🦴', q: 'bone skeleton anatomy' },
  { emoji: '👃', q: 'nose smell sniff' },
  { emoji: '👂', q: 'ear listen hear audio' },
  { emoji: '👅', q: 'tongue taste lick' },
  { emoji: '👄', q: 'mouth lips kiss speak' },
  { emoji: '🫦', q: 'biting lip nervous' },
  { emoji: '🩸', q: 'drop blood medical' },
  { emoji: '🪬', q: 'hamsa hand protection' },
  { emoji: '🪧', q: 'placard protest sign' },
  { emoji: '🪪', q: 'id card identification' },
  { emoji: '⚧️', q: 'transgender symbol pride' },
  { emoji: '🏳️‍🌈', q: 'rainbow flag pride lgbtq' },
  { emoji: '🏳️‍⚧️', q: 'trans flag pride' },
  { emoji: '🇺🇸', q: 'usa america flag united states' },
  { emoji: '🇬🇧', q: 'uk britain flag great britain' },
  { emoji: '🇨🇦', q: 'canada flag maple' },
  { emoji: '🇯🇵', q: 'japan flag' },
  { emoji: '🇩🇪', q: 'germany flag deutsch' },
  { emoji: '🇫🇷', q: 'france flag' },
  { emoji: '🇮🇳', q: 'india flag' },
  { emoji: '🇧🇷', q: 'brazil flag' },
  { emoji: '🇦🇺', q: 'australia flag' },
  { emoji: '🇰🇷', q: 'korea south flag' },
  { emoji: '🇨🇳', q: 'china flag' },
  { emoji: '🇲🇽', q: 'mexico flag' },
  { emoji: '🇪🇸', q: 'spain flag' },
  { emoji: '🇮🇹', q: 'italy flag' },
  { emoji: '🇳🇱', q: 'netherlands flag holland' },
  { emoji: '🇸🇪', q: 'sweden flag' },
  { emoji: '🇨🇭', q: 'switzerland flag' },
  { emoji: '🇸🇬', q: 'singapore flag' },
  { emoji: '🇦🇪', q: 'uae flag dubai' },
  { emoji: '🇳🇬', q: 'nigeria flag' },
  { emoji: '🇿🇦', q: 'south africa flag' },
  { emoji: '🇪🇬', q: 'egypt flag' },
  { emoji: '🇦🇷', q: 'argentina flag' },
  { emoji: '🇨🇱', q: 'chile flag' },
  { emoji: '🇨🇴', q: 'colombia flag' },
  { emoji: '🇵🇪', q: 'peru flag' },
  { emoji: '🇵🇹', q: 'portugal flag' },
  { emoji: '🇵🇱', q: 'poland flag' },
  { emoji: '🇹🇷', q: 'turkey flag' },
  { emoji: '🇻🇳', q: 'vietnam flag' },
  { emoji: '🇹🇭', q: 'thailand flag' },
  { emoji: '🇮🇩', q: 'indonesia flag' },
  { emoji: '🇵🇭', q: 'philippines flag' },
  { emoji: '🇳🇿', q: 'new zealand flag' },
  { emoji: '🇮🇪', q: 'ireland flag' },
  { emoji: '🇦🇹', q: 'austria flag' },
  { emoji: '🇧🇪', q: 'belgium flag' },
  { emoji: '🇨🇿', q: 'czechia flag' },
  { emoji: '🇭🇺', q: 'hungary flag' },
  { emoji: '🇷🇴', q: 'romania flag' },
  { emoji: '🇺🇦', q: 'ukraine flag' },
  { emoji: '🇮🇱', q: 'israel flag' },
  { emoji: '🇸🇦', q: 'saudi arabia flag' },
  { emoji: '🇵🇰', q: 'pakistan flag' },
  { emoji: '🇧🇩', q: 'bangladesh flag' },
  { emoji: '🇰🇪', q: 'kenya flag' },
  { emoji: '🇬🇭', q: 'ghana flag' },
  { emoji: '🇪🇹', q: 'ethiopia flag' },
  { emoji: '🇲🇦', q: 'morocco flag' },
  { emoji: '🇬🇷', q: 'greece flag' },
  { emoji: '🇫🇮', q: 'finland flag' },
  { emoji: '🇳🇴', q: 'norway flag' },
  { emoji: '🇩🇰', q: 'denmark flag' },
  { emoji: '0️⃣', q: 'zero keycap number digit' },
  { emoji: '1️⃣', q: 'one keycap number digit' },
  { emoji: '2️⃣', q: 'two keycap number digit' },
  { emoji: '3️⃣', q: 'three keycap number digit' },
  { emoji: '4️⃣', q: 'four keycap number digit' },
  { emoji: '5️⃣', q: 'five keycap number digit' },
  { emoji: '6️⃣', q: 'six keycap number digit' },
  { emoji: '7️⃣', q: 'seven keycap number digit' },
  { emoji: '8️⃣', q: 'eight keycap number digit' },
  { emoji: '9️⃣', q: 'nine keycap number digit' },
  { emoji: '🔟', q: 'ten keycap number' },
  { emoji: '🔢', q: 'input numbers math' },
  { emoji: '#️⃣', q: 'hash pound hashtag number' },
  { emoji: '*️⃣', q: 'asterisk keycap star' },
  { emoji: '▶️', q: 'play button triangle media' },
  { emoji: '⏸️', q: 'pause button media' },
  { emoji: '⏹️', q: 'stop button media' },
  { emoji: '⏭️', q: 'next track media' },
  { emoji: '⏮️', q: 'previous track media' },
  { emoji: '⏯️', q: 'play pause media' },
  { emoji: '🔀', q: 'shuffle tracks random' },
  { emoji: '🔁', q: 'repeat loop media' },
  { emoji: '🔂', q: 'repeat single once' },
  { emoji: '🔄', q: 'counterclockwise arrows refresh sync' },
  { emoji: '🔃', q: 'clockwise vertical arrows reload' },
  { emoji: '🎦', q: 'cinema movie film' },
  { emoji: '🔅', q: 'dim brightness low' },
  { emoji: '🔆', q: 'bright brightness high' },
  { emoji: '📶', q: 'signal antenna bars wifi' },
  { emoji: '📳', q: 'vibration mode phone' },
  { emoji: '📴', q: 'mobile off airplane mode' },
  { emoji: '♀️', q: 'female sign woman gender' },
  { emoji: '♂️', q: 'male sign man gender' },
  { emoji: '⚕️', q: 'medical symbol health caduceus' },
  { emoji: '♾️', q: 'infinity forever endless' },
  { emoji: '♻️', q: 'recycle green environment' },
  { emoji: '⚜️', q: 'fleur-de-lis decorative' },
  { emoji: '🔱', q: 'trident emblem poseidon' },
  { emoji: '📛', q: 'name badge id tag' },
  { emoji: '🔰', q: 'japanese beginner symbol leaf' },
  { emoji: '⭕', q: 'hollow red circle o' },
  { emoji: '❌', q: 'cross mark x wrong no' },
  { emoji: '❎', q: 'cross mark button square' },
  { emoji: '➕', q: 'plus math add' },
  { emoji: '➖', q: 'minus math subtract' },
  { emoji: '➗', q: 'divide math division' },
  { emoji: '➰', q: 'curly loop' },
  { emoji: '➿', q: 'double curly loop' },
  { emoji: '〽️', q: 'part alternation mark' },
  { emoji: '✳️', q: 'eight spoked asterisk star' },
  { emoji: '✴️', q: 'eight pointed black star' },
  { emoji: '❇️', q: 'sparkle shine' },
  { emoji: '‼️', q: 'double exclamation wow' },
  { emoji: '⁉️', q: 'exclamation question interrobang' },
  { emoji: '❓', q: 'question mark red' },
  { emoji: '❔', q: 'white question mark outline' },
  { emoji: '❕', q: 'white exclamation mark' },
  { emoji: '❗', q: 'exclamation mark red alert' },
  { emoji: '〰️', q: 'wavy dash' },
  { emoji: '©️', q: 'copyright legal' },
  { emoji: '®️', q: 'registered trademark' },
  { emoji: '™️', q: 'trademark brand' },
  { emoji: '🔠', q: 'input latin uppercase abc' },
  { emoji: '🔡', q: 'input latin lowercase' },
  { emoji: '🔣', q: 'input symbols' },
  { emoji: '🔤', q: 'input latin letters' },
  { emoji: '🅰️', q: 'a button blood type' },
  { emoji: '🆎', q: 'ab button blood' },
  { emoji: '🅱️', q: 'b button blood type' },
  { emoji: '🆑', q: 'cl clear symbol' },
  { emoji: '🆒', q: 'cool words sunglasses' },
  { emoji: '🆓', q: 'free no cost' },
  { emoji: 'ℹ️', q: 'information i help' },
  { emoji: '🆔', q: 'id identity card' },
  { emoji: 'Ⓜ️', q: 'circled m metro' },
  { emoji: '🆕', q: 'new badge fresh' },
  { emoji: '🆖', q: 'ng no good' },
  { emoji: '🅾️', q: 'o button blood type' },
  { emoji: '🆗', q: 'ok okay good' },
  { emoji: '🅿️', q: 'p parking' },
  { emoji: '🆘', q: 'sos help emergency' },
  { emoji: '🆙', q: 'up exclamation level up' },
  { emoji: '🆚', q: 'versus vs battle' },
  { emoji: '🈁', q: 'katakana here japanese' },
  { emoji: '🈯', q: 'reserved japanese' },
  { emoji: '🈳', q: 'vacancy japanese' },
  { emoji: '🈵', q: 'no vacancy full japanese' },
  { emoji: '🈚', q: 'free charge japanese' },
  { emoji: '🈸', q: 'application japanese' },
  { emoji: '🈺', q: 'open for business japanese' },
  { emoji: '🈷️', q: 'monthly amount japanese' },
  { emoji: '㊗️', q: 'congratulations japanese' },
  { emoji: '㊙️', q: 'secret japanese' },
  { emoji: '🔴', q: 'red circle dot record' },
  { emoji: '🟠', q: 'orange circle' },
  { emoji: '🟡', q: 'yellow circle' },
  { emoji: '🟢', q: 'green circle go online' },
  { emoji: '🔵', q: 'blue circle' },
  { emoji: '🟣', q: 'purple circle' },
  { emoji: '🟤', q: 'brown circle' },
  { emoji: '⚫', q: 'black circle' },
  { emoji: '⚪', q: 'white circle' },
  { emoji: '🟥', q: 'red square' },
  { emoji: '🟧', q: 'orange square' },
  { emoji: '🟨', q: 'yellow square' },
  { emoji: '🟩', q: 'green square' },
  { emoji: '🟦', q: 'blue square' },
  { emoji: '🟪', q: 'purple square' },
  { emoji: '🟫', q: 'brown square' },
  { emoji: '⬛', q: 'black large square' },
  { emoji: '⬜', q: 'white large square' },
  { emoji: '◼️', q: 'black medium square' },
  { emoji: '◻️', q: 'white medium square' },
  { emoji: '◾', q: 'black medium small square' },
  { emoji: '◽', q: 'white medium small square' },
  { emoji: '▪️', q: 'black small square' },
  { emoji: '▫️', q: 'white small square' },
  { emoji: '🔶', q: 'large orange diamond' },
  { emoji: '🔷', q: 'large blue diamond' },
  { emoji: '🔸', q: 'small orange diamond' },
  { emoji: '🔹', q: 'small blue diamond' },
  { emoji: '🔺', q: 'red triangle pointed up' },
  { emoji: '🔻', q: 'red triangle pointed down' },
  { emoji: '💠', q: 'diamond shape dot inside' },
  { emoji: '🔘', q: 'radio button select' },
  { emoji: '🔳', q: 'white square button' },
  { emoji: '🔲', q: 'black square button' },
  { emoji: '🏁', q: 'chequered flag finish racing' },
  { emoji: '🚩', q: 'triangular flag post location' },
  { emoji: '🎌', q: 'crossed flags japanese' },
  { emoji: '🏴', q: 'black flag pirate' },
  { emoji: '🏳️', q: 'white flag surrender peace' },
  { emoji: '🏴‍☠️', q: 'pirate flag skull crossbones' },
];
